language: java
jdk:
 - oraclejdk8
 
before_install:
  - chmod +x mvnw
  
cache:
  directories:
  - $HOME/.m2
  
deploy:
   provider: heroku
   api-key: 
      secure: 76d45c69-e8c6-44a8-a1f7-6577bf3d91fb
   app: e-weather-web-demo